DROP DATABASE IF EXISTS meetingproject;

CREATE DATABASE IF NOT EXISTS meetingproject;
use meetingproject;

CREATE TABLE IF NOT EXISTS user
 (
   id_user INTEGER(5) AUTO_INCREMENT NOT NULL  ,
   NOMREGION VARCHAR(30) NULL  ,
   DESCRIPTION VARCHAR(60) NULL
   , PRIMARY KEY (CODEREGION)
 )
 comment = "";

CREATE TABLE IF NOT EXISTS CONTRAT_C
 (
   CODECC INTEGER(5) AUTO_INCREMENT NOT NULL  ,
   CODER INTEGER(5) NOT NULL  ,
   CODEA INTEGER(5) NOT NULL  ,
   TARIFCC DECIMAL(10,2) NULL  ,
   DATESIGNATURECC VARCHAR(10) NULL  ,
   ETATCC INTEGER(1) NULL
   , PRIMARY KEY (CODECC)
 )
 comment = "";



CREATE TABLE IF NOT EXISTS PROPRIETAIRE
